# Generated by Django 2.1 on 2020-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='userName',
            field=models.CharField(default=-1.0, max_length=500),
            preserve_default=False,
        ),
    ]
