# Generated by Django 2.1 on 2020-08-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patID',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Patient'),
            preserve_default=False,
        ),
    ]
