# Generated by Django 2.1 on 2020-08-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200805_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patID',
            new_name='pat',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pat',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Patient'),
            preserve_default=False,
        ),
    ]
