# Generated by Django 2.1 on 2020-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200805_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patID',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagType',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='docName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userName',
            field=models.EmailField(blank=True, max_length=500),
        ),
    ]
