# Generated by Django 2.1 on 2020-08-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200805_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pat',
        ),
        migrations.AddField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Doctor'),
            preserve_default=False,
        ),
    ]