# Generated by Django 2.1 on 2020-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200813_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userName',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
    ]
