# Generated by Django 2.1 on 2020-08-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20200813_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='pat',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Doctor'),
        ),
    ]
