# Generated by Django 2.1 on 2020-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20200805_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userName',
            field=models.EmailField(max_length=500),
        ),
    ]
