# Generated by Django 2.1 on 2020-08-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20200816_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagType',
            new_name='diag',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pat',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Patient'),
        ),
    ]
