# Generated by Django 2.1 on 2020-08-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_auto_20200816_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('userName',)},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('userName',)},
        ),
    ]
