# Generated by Django 2.1 on 2020-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_auto_20200817_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userName',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
