# Generated by Django 2.1 on 2020-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_auto_20200817_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userName',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userName',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
