# Generated by Django 2.1 on 2020-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_auto_20200819_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='userName',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.EmailField(blank=True, max_length=500, unique=True),
        ),
    ]
